# Generated by Django 5.1.7 on 2025-03-17 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('material_type', models.CharField(choices=[('metal', 'Metal'), ('composite', 'Composite'), ('polymer', 'Polymer'), ('other', 'Other')], default='metal', max_length=20)),
                ('lot_number', models.CharField(max_length=100, unique=True)),
                ('supplier', models.CharField(max_length=255)),
                ('received_date', models.DateField()),
                ('heat_number', models.CharField(blank=True, max_length=100, null=True)),
                ('certification_file', models.FileField(blank=True, null=True, upload_to='certifications/')),
                ('quantity', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('available', 'Available'), ('used', 'Used')], default='available', max_length=20)),
            ],
        ),
    ]
